source 'https://rubygems.org'

gem 'rails', '4.2.0'
gem 'pg'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby


gem 'sdoc', '~> 0.4.0', group: :doc

group :development, :test do

  gem 'byebug'

  gem 'web-console', '~> 2.0'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
